#include<stdio.h>
#include<stdlib.h>
#include<conio.h>
#include<string.h>

struct node
{
	char hostIp[13];
	char identd[4];
	char userId[5];
	char day[3];
	char month[4];
	char year[5] ;
	char hour[3];
	char minute[3];
	char second[3];
	char zone[6];
	char numericValue[10];
	char method[8];
	char type[2];
	char protocol[15];
	char statusCode[4];
	char objectSize[10];
	char browserUsed[20];
	char **compatibleBrowser;
	int numComBrows;
	struct node* next;
};
struct node *start=NULL;
int countChar(char *str,char ch)
{
	int count=0,ind=0;
	while(str[ind]!='\0')
	{
		if(str[ind]==ch)
			count++;
		ind++;
	}
	return count;
}
int func(char *inpStr,char *outStr,int index,char ch )
{
		int ind=0;
		
		while(inpStr[index]!='\0'&& inpStr[index]!=ch)
		{
			outStr[ind]=inpStr[index];
			ind++;
			index++;
		}
		outStr[ind]='\0';
		return index;
}
void printList()
{
	int i;
	struct node* temp=start;
	while(temp!=NULL)
	{
		printf("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t",temp->hostIp,temp->day,temp->month,temp->year,temp->hour,temp->minute,temp->second,temp->zone,temp->method,temp->type,temp->protocol,temp->statusCode,temp->objectSize,temp->browserUsed);
	
		for(i=0;i<temp->numComBrows;i++)
		{
			printf("%s\t",temp->compatibleBrowser[i]);
		}

//	printf("%s\n",temp->hostIp);	
		temp=temp->next;
	}
}
void addNode(struct node** refStart,struct node* temp)
{
	if(*refStart==NULL)
		*refStart=temp;
	else
	{
		temp->next=*refStart;
		*refStart=temp;
	}	
}
void parse()
{
	char *ch,*tempCh,c;
	int index,count,i;
	FILE *fp;
	struct node *temp=NULL,*lastNode=NULL;
	
	ch=(char*)calloc(100,sizeof(char));
	tempCh=(char*)calloc(50,sizeof(char));
	
	fp=fopen("testLog.log","r");
	
	do{
		
			temp=(struct node*)malloc(sizeof(struct node));
			temp->next=NULL;
		
			fscanf(fp,"%s %s %s %s",temp->hostIp,temp->identd,temp->userId,ch);
			index=func(ch,temp->day,1,'/');
			index=func(ch,temp->month,index+1,'/');
			index=func(ch,temp->year,index+1,':');
			index=func(ch,temp->hour,index+1,':');
			index=func(ch,temp->minute,index+1,':');
			index=func(ch,temp->second,index+1,':');
			fscanf(fp,"%s",temp->zone);
			temp->zone[strlen(temp->zone)-1]='\0';
			fscanf(fp,"%s",temp->numericValue);
			fscanf(fp,"%s",ch);
			func(ch,temp->method,1,'\0');
			fscanf(fp,"%s",ch);
			func(ch,temp->type,1,'/');
			fscanf(fp,"%s",temp->protocol);
			temp->protocol[strlen(temp->protocol)-1]='\0';
			fscanf(fp,"%s",temp->statusCode);
			fscanf(fp,"%s",temp->objectSize);
			fscanf(fp,"%s",ch);
			fscanf(fp,"%s",ch);
			func(ch,temp->browserUsed,1,'\0');
			fscanf(fp,"%s",ch);
			
			index=0;
			while ((c = getc(fp)) != ')' && c != EOF)
				ch[index++]=c;
		
			ch[index]='\0';
			c=getc(fp);
	
			count=countChar(ch,';');
			count++;
			temp->compatibleBrowser=(char**)malloc(sizeof(char*)*count);
			temp->numComBrows=count;
			index=0;
			for(i=0;i<count;i++)
			{
				index=func(ch,tempCh,index+1,';');
				temp->compatibleBrowser[i]=(char*)malloc(sizeof(char)*50);
				strcpy(temp->compatibleBrowser[i],tempCh);	
			}
			addNode(&start,temp);
	}while(!feof(fp));
	temp=start;
	start=start->next;
	free(temp);
	fclose(fp);

}
void statusStat()
{
	struct node*temp=start;
	int **hash,i=0,j=0,num,genNum;
	char status[4];
	
	hash=(int**)calloc(5,sizeof(int*));
	for(i=0;i<5;i++)
	{
		hash[i]=(int*)calloc(17,sizeof(int));
	}
	while(temp!=NULL)
	{
		strcpy(status,temp->statusCode);
		num=(status[1]-48)*10+(status[2]-48);
		(hash[status[0]-49][num])++;
		temp=temp->next;
	}
	printf("count\tstatus \n");
	for(i=0;i<5;i++)
	{
		for(j=0;j<17;j++)
		{
			if(hash[i][j]>0)
			{
				genNum=i+1;
				genNum=genNum*100+j;
				printf("%d\t%d\n",hash[i][j],genNum);
			}
		}
	}
	
}
void deleteBot()
{
	struct node* temp=start,*previous=NULL;
	
	while(temp!=NULL)
	{
		if(strstr(temp->browserUsed,"bot"))
		{
			if(temp==start)
			{
				start=start->next;
				printf("deleting bot with %s host ip",temp->hostIp);
				free(temp);
				temp=start;
			}
			else
			{
				previous->next=temp->next;
				printf("deleting bot with %s host ip",temp->hostIp);
				free(temp);
				temp=previous->next;
			}
		}
		else
		{
			previous=temp;
			temp=temp->next;
			
		}
		
	}
//	printList(start);
}
void showBoot()
{
	struct node* temp=start;
	
	while(temp!=NULL)
	{
		if(strstr(temp->browserUsed,"bot"))
			printf("Boot request generated by ip %s \n",temp->hostIp);
	
		temp=temp->next;	
	}
}
void main()
{
	int choice;
	parse();
//	printList(start);
	do
	{
		printf("\nMenu\n1.status wise stats\n2.Delete Bots\n3.Show boot generated request\n4.Show log\n5.exit\n");
		scanf("%d",&choice);
		switch(choice)
		{
			case 1: 
				statusStat();
				break;
			case 2:
				deleteBot();
				break;
			case 3:
				showBoot();
				break;
			case 4:
				printList();
				break;
			case 5:
				printf("programs ends");	
				break;
			default:
				printf("wrong input");
					break;
		}
		
	}while(choice!=4);
}
